---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
 name: inspec

platforms:
  - name: ubuntu-14.04
    customize:
      cpus: 2
      memory: 1024
    driver:
      network:
        - ["forwarded_port", {guest: 8080, host: 8080}]
        - ["private_network", {ip: "192.168.0.50"}]

suites:
  - name: default
    run_list:
      - recipe[aar-workshop::default]
    attributes:
