name 'aar-workshop'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures aar-workshop'
long_description 'Installs/Configures aar-workshop'
version '0.1.0'
